export const metadata = {
    title: 'CRUD App | Post',
    description: 'Generated by create next app',}

export default function Post() {
    return (
      <div>
        <h1>Post Page</h1>
      </div>
    )
  }