export const metadata = {
    title: 'CRUD App | Post Detail',
    description: 'Generated by create next app',}

export default function PostDetail({params}: {params: {postid: string}}) {
    return (
      <div>
        <h1>Post {params.postid[0]}</h1>
      </div>
    )
  }