export const metadata = {
    title: 'CRUD App | About',
    description: 'Generated by create next app',}

export default function About() {
    return (
      <div>
        <h1>About Page</h1>
      </div>
    )
  }