"use client"
import{SyntheticEvent, useState} from "react";
import { useRouter } from "next/navigation";
type Product ={
    id: number;
    title: string;
    price: number;
  }
export const metadata = {
    title: 'CRUD App | Add Products',
    description: 'Generated by create next app',}

export default function UpdateProducts(product: Product) {
    const [title, setTitle] = useState(product.title);
    const [price, setPrice] = useState(product.price);
    const [modal, setModal] = useState(false);
    const [isMutating, setIsMutating] = useState(false);
    const router = useRouter();

    async function handleUpdate(e:SyntheticEvent) {
        e.preventDefault();
        setIsMutating(true);
        await fetch(`http://localhost:5000/products/${product.id}`, {
            method:'PATCH',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                title: title,
                price: price,
            }),
        });
        setIsMutating(false);
        router.refresh();
        setModal(false);
    }
    function handleChange(){
        setModal(!modal);
    }
    return (
      <div>
        <button className="btn btn-info btn-sm" onClick={handleChange}>Edit</button>
        <input type="checkbox" checked={modal} onChange={handleChange} className="modal-toggle" />
        <div className="modal">
            <div className="modal-box">
                <h3 className="font-bold text-lg">Edit {product.title}</h3>
                <form onSubmit={handleUpdate} action="">
                    <div className="form-control">
                        <label className="label font-bold">Nama Product</label>
                        <input placeholder="Nama Product" value={title} onChange={(e) => setTitle(e.target.value)} type="text" className="input w-full input-bordered" />
                    </div>
                    <div className="form-control">
                        <label className="label font-bold">Harga</label>
                        <input placeholder="Harga Product"  value={price} onChange={(e) => setPrice(Number(e.target.value))} type="text" className="input w-full input-bordered" />
                    </div>
                    <div className="modal-action">
                        <button type="button" className="btn" onClick={handleChange}>Close</button>
                        {!isMutating ?(
                            <button type="submit" className="btn btn-primary">Update</button>
                            
                            ):(
                                <button type="button" className="btn loading">Updating...</button>
                            )
                    
                        }
                    </div>
                </form>
            </div>
        </div>
      </div>
    )
  }