"use client"

import React, { useEffect, useState } from 'react';
import Header from './komponen/header';

export const metadata = {
  title: 'CRUD App | Products',
  description: 'Generated by create next app',
};

type Data = {
  id: number;
  kegiatan: string;
};

async function getData() {
  const res = await fetch('http://localhost:1337/api/to-dos', { cache: 'no-store' });
  return res.json();
}

export default function Home() {
  const [data, setData] = useState<Data[]>([]);

  useEffect(() => {
    async function fetchData() {
      const fetchedData = await getData();
      setData(fetchedData.data);
    }
    fetchData();
  }, []);

  return (
    <div>
      <Header />
      {data.map((item) => (
        <p key={item.id}>{item.kegiatan}</p>
      ))}
    </div>
  );
}
