"use client"
import{SyntheticEvent, useState} from "react";
import { useRouter } from "next/navigation";
export const metadata = {
    title: 'CRUD App | Add Products',
    description: 'Generated by create next app',}

export default function AddProducts() {
    const [title, setTitle] = useState("");
    const [price, setPrice] = useState("");
    const [modal, setModal] = useState(false);
    const [isMutating, setIsMutating] = useState(false);
    const router = useRouter();

    async function handleSubmit(e:SyntheticEvent) {
        e.preventDefault();
        setIsMutating(true);
        await fetch('http://localhost:5000/products', {
            method:'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                title: title,
                price: price,
            }),
        });
        setIsMutating(false);
        setTitle("");
        setPrice("");
        router.refresh();
        setModal(false);
    }
    function handleChange(){
        setModal(!modal);
    }
    return (
      <div>
        <button className="btn" onClick={handleChange}>Add New</button>
        <input type="checkbox" checked={modal} onChange={handleChange} className="modal-toggle" />
        <div className="modal">
            <div className="modal-box">
                <h3 className="font-bold text-lg">Add New Product</h3>
                <form onSubmit={handleSubmit} action="">
                    <div className="form-control">
                        <label className="label font-bold">Nama Product</label>
                        <input placeholder="Nama Product" value={title} onChange={(e) => setTitle(e.target.value)} type="text" className="input w-full input-bordered" />
                    </div>
                    <div className="form-control">
                        <label className="label font-bold">Harga</label>
                        <input placeholder="Harga Product"  value={price} onChange={(e) => setPrice(e.target.value)} type="text" className="input w-full input-bordered" />
                    </div>
                    <div className="modal-action">
                        <button type="button" className="btn" onClick={handleChange}>Close</button>
                        {!isMutating ?(
                            <button type="submit" className="btn btn-primary">Save</button>
                            
                            ):(
                                <button type="button" className="btn loading">Saving...</button>
                            )
                    
                        }
                    </div>
                </form>
            </div>
        </div>
      </div>
    )
  }