import { cache } from "react";
import AddProducts from "./AddProducts";
import DeleteProducts from "./DeleteProduct";
import UpdateProducts from "./UpdateProduct";

export const metadata = {
  title: 'CRUD App | Products',
  description: 'Generated by create next app',}

type Product ={
  id: number;
  title: string;
  price: number;
}

async function getProducts() {
  const res = await fetch('http://localhost:5000/products', {cache: 'no-store'});
  return res.json();
}

export default async function Products() {
  const products: Product[] = await getProducts();
    return (
      <div className="py-10 px-10">
        <div className="py-2">
          <AddProducts/>
        </div>
        <table className="table w-full">
          <thead>
            <tr>
              <th>#</th>
              <th>Nama Product</th>
              <th>Harga</th>
              <th>Aksi</th>
            </tr>
          </thead>
          <tbody>
          {products.map((product, index) =>(
            <tr key={product.id}>
              <td>{index + 1}</td>
              <td>{product.title}</td>
              <td>{product.price}</td>
              <td className="flex">
                <UpdateProducts{...product}/>
                <DeleteProducts{...product}/></td>
            </tr>
        ))}
          </tbody>
        </table>
      </div>
    )
  }